# Generated by Django 5.1.4 on 2025-01-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_USER', '0004_permissions_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={},
        ),
    ]
