# Generated by Django 5.1.4 on 2025-01-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_USER', '0005_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='participants', to='AUTH_USER.permissions'),
        ),
    ]
