# Generated by Django 5.1.4 on 2025-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_USER', '0006_alter_permission_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='AUTH_USER.permissions'),
        ),
    ]
