# Generated by Django 5.1.4 on 2025-01-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_USER', '0007_remove_permission_permission_permission_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=150, unique=True),
        ),
    ]
