# Generated by Django 5.1.4 on 2025-01-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH_USER', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
