# Generated by Django 5.1.4 on 2025-01-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='changed_cost',
            new_name='changed_price',
        ),
    ]
