# Generated by Django 5.1.4 on 2025-01-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
