# Generated by Django 5.1.4 on 2025-01-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_changed_cost_recipe_changed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientgram',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
