# Generated by Django 5.1.4 on 2025-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stock_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
