# Generated by Django 5.1.4 on 2025-01-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
