# Generated by Django 5.1.4 on 2025-01-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='real_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='recipe',
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recipe'),
        ),
    ]
