# Generated by Django 5.1.4 on 2025-01-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_real_price_remove_product_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipe'),
        ),
    ]
