# Generated by Django 5.1.4 on 2025-01-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_real_price_alter_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='real_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
