# Generated by Django 5.1.4 on 2025-01-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_status_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='size',
        ),
    ]
