# Generated by Django 5.1.4 on 2025-01-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_stock_price_stock_real_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='real_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
    ]
