# Generated by Django 5.1.4 on 2025-01-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stock_real_price_alter_stock_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientgram',
            old_name='measure',
            new_name='measurement',
        ),
    ]
