# Generated by Django 5.1.4 on 2025-01-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_measure_ingredientgram_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientgram',
            name='measure_unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.measurement'),
        ),
    ]
