# Generated by Django 5.1.4 on 2025-01-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ingredientgram_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientgram',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.measurement'),
        ),
    ]
