# Generated by Django 5.1.4 on 2025-01-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ingredientgram_measure_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientgram',
            old_name='measurement',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredientgram',
            name='measure_unit',
        ),
    ]
