# Generated by Django 5.1.4 on 2025-01-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_recipe_change_price_stock_user_sellproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
