# Generated by Django 5.1.4 on 2025-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientgram',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='measurement_unit',
            field=models.ManyToManyField(to='api.measurement'),
        ),
    ]
