# Generated by Django 5.1.4 on 2025-01-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_ingredientgram_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='measurement_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.measurement'),
        ),
    ]
